# build stage
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_BASE_URL
ARG VITE_REALTIME_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_REALTIME_URL=$VITE_REALTIME_URL
RUN npm run build

# production stage
FROM nginx:alpine as production
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
